### ISSUE TITLE
Use `version(FreeStanding)` insteadof version(bare_metal)

### ISSUE THREAD

**Issue by ZombineDev** [Vild/PowerNex#26]
Which was added with [PR 4367](https://github.com/D-Programming-Language/dmd/pull/4367). I hope in the future there will be more D libraries suitable for kernel/embedded programming such as yours. Using a common version identifier, such as FreeStanding can help with interoperability between libraries.
I know that large portions of low-level code is not reusable, but there is often code like range algorithms, that has little to now run-time requirement and as such is suitable for this domain.

**Comment by Vild** [comment]
Sure.
The current object.d file is almost a 100% copy of Adam D. Ruppes "minimal.zip" minimal d kernel.

I have planned a rework of the object.d file, so I guess I will implement this too.

Thank you for the notification! :+1:

**Comment by Vild** [comment]
FreeStanding is currently a reserved version, and there is compiler switch to enable that version, at this time sadly.

**Comment by Vild** [comment]
I have patched dmd to define the FreeStanding version, but currently the version is not used anywhere.
