### ISSUE TITLE
Cannot download toolchain

### ISSUE THREAD

**Issue by theokeist** [Vild/PowerNex#51]
After click on link just showing page with: No site configured for this domain!

**Comment by M4GNV5** [comment]
gg .tk domains

**Comment by Vild** [comment]
Sorry about that, I'm restructuring my domains.
Please use this link until I have configured all my domains: https://mega.nz/#!cx913RZZ!i3lHemFSPRT5kgdbGjS9YgXLKx0bV84Jg50cOYOdxUg

**Comment by Vild** [comment]
Fixed download link in: 353afaa7957456195651dd836cd8dddad03104ee
