### ISSUE TITLE
autoExit is not mapped executable in usermode

### ISSUE THREAD

**Issue by M4GNV5** [Vild/PowerNex#56]
when the function passed to Scheduler.Clone returns it jumps to autoExit as intended however autoExit is not mapped as executable and thus raises a page fault .

https://github.com/Vild/PowerNex/blob/master/Kernel/src/Task/Scheduler.d#L23-L30

**Comment by Vild** [comment]
*Not mapped as userspace.

Fix: Run the Exit syscall in userspace.

**Comment by M4GNV5** [comment]
Yeah of course running exit fixes it however then there shouldnt be a autoExit function it returns to.
