### ISSUE TITLE
Internationalization/Multi-byte API support

### ISSUE THREAD

**Issue by WebFreak001** [Vild/PowerNex#70]
Please keep other languages/locales in mind and maybe use wstring instead of string for API calls. For example the boot console should support printing üöä or even japanese/chinese text and there should be some API for localizing things. Keeping this in mind early in development will help in the future and also attract more foreign users.

**Comment by Vild** [comment]
Fixed in 24160fe2d62a0451bc5ab89ef369b803df86d13f
