### ISSUE TITLE
powernexos.org/ security

### ISSUE THREAD

**Issue by nguyengiabach1201** [Vild/PowerNex#92]
[powernexos.org/](powernexos.org/) Need a https or else it would be insecurity and be ignore by people ://

**Comment by Hacker1245** [comment]
You don't need https on something that doesn't take any sensitive info.

**Comment by nguyengiabach1201** [comment]
But it looks scary :skull: and insecurity. Also, it takes no effort to give the site a HTTPS

**Comment by Vild** [comment]
I added https to both https://powernexos.org/ & https://powernex.net/ but I never had any website for it. So it didn't really matter.

**Comment by WebFreak001** [comment]
looking at the website, the future™ of powernex is looking bright (it's missing the mascot though)

**Comment by nguyengiabach1201** [comment]
> I added https to both https://powernexos.org/ & https://powernex.net/ but I never had any website for it. So it didn't really matter.

Can I help make one?

**Comment by Vild** [comment]
No need for a website while PowerNex is dead, and I rather do it myself. (Like most, if not all, PowerNex code)
